FROM ubuntu:19.10

ADD sources.list /etc/apt/sources.list 

RUN apt-get update --fix-missing && apt-get install -y \
    vim \
    git \
    wget \
    gcc \
    g++ \
    cmake \
    libboost-all-dev \
    libevent-dev \
    libdouble-conversion-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    libiberty-dev \
    liblz4-dev \
    liblzma-dev \
    libsnappy-dev \
    make \
    zlib1g-dev \
    binutils-dev \
    libjemalloc-dev \
    libssl-dev \
    pkg-config \
    libunwind8-dev \
    libelf-dev \
    libdwarf-dev \
    libsodium-dev \
    flex \
    bison
